model_params:
  name: '3d_VanillaVAE'
  in_channels: 1
  latent_dim: 128


data_params:
  data_path: '/scratch/connectome/mieuxmin/UKB_sample' #40,000 path : "/storage/bigdata/UKB/brain_prep/1.sMRI/2.sMRI_fs_cropped/"
  train_batch_size: 2
  val_batch_size:  2
  patch_size: 64
  num_workers: 4
  img_shape: [96,96,96] #추가한 arugment


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 5

logging_params:
  save_dir: "logs/"
  name: "3d_vae"
  

